[build]
  publish = "dist"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

# SPA fallback for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Branch deploy settings
[context.staging]
  publish = "dist"
  
[context.production]
  publish = "dist"
  
# Environment-specific settings
[context.staging.environment]
  NODE_ENV = "staging"
  
[context.production.environment]
  NODE_ENV = "production"
