[build]
  command = "npm run build"
  publish = ".sanity"

[build.environment]
  NODE_VERSION = "22"

# Cabeçalhos de segurança (opcional)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
