[build]
  publish = ".sanity"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

# SPA fallback para o Studio (opcional, se você quiser abrir URLs internas)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cabeçalhos de segurança (opcional)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
