[build]
  command = "npm run build -w studio"
  publish = "apps/studio/.sanity"

[build.environment]
  NODE_VERSION = "22"

# SPA fallback para o Studio, caso necessário
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Opcional: segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
