name: Web Production | Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - apps/web/**
      - .github/workflows/web-prod.yml
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Web (Production)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
        working-directory: apps/web

      - name: Build Web
        run: npm run build
        working-directory: apps/web
        env:
          VITE_SANITY_PROJECT_ID: ${{ secrets.VITE_SANITY_PROJECT_ID }}
          VITE_SANITY_DATASET: production

      - name: Deploy to Netlify
        run: |
          npx netlify deploy \
            --build \
            --context production \
            --prod \
            --dir apps/web/dist \
            --message "Deploy Web Production (${GITHUB_SHA})" \
            --site ${{ secrets.NETLIFY_SITE_ID }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
