name: Web Staging | Build and Deploy

on:
  push:
    branches:
      - staging
    paths:
      - apps/web/**
      - .github/workflows/web-staging.yml
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Web (Staging)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
        working-directory: apps/web

      - name: Build Web
        run: npm run build
        working-directory: apps/web
        env:
          VITE_SANITY_PROJECT_ID: ${{ secrets.VITE_SANITY_PROJECT_ID }}
          VITE_SANITY_DATASET: staging

      - name: Deploy to Netlify
        run: |
          npx netlify deploy \
            --build \
            --context deploy-preview \
            --alias staging \
            --dir apps/web/dist \
            --message "Deploy Web Staging (${GITHUB_SHA})" \
            --site ${{ secrets.NETLIFY_SITE_ID }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
